version: "3.8"
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: jazz-in-toronto
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
